services:
  api:
    build:
      context: ./hianime-api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  bot:
    build:
      context: .             # ← point at repo root
      dockerfile: Dockerfile # ← if your bot Dockerfile is at /root/utest1/Dockerfile
    depends_on:
      api:
        condition: service_healthy
    environment:
      - ANIWATCH_API_BASE=http://api:4000/api/v2/hianime
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
    restart: on-failure
